[package]
name = "readstor"
version = "0.3.0"
description = "A CLI for Apple Books annotations"
readme = "README.md"
license = "MIT OR Apache-2.0"
homepage = "https://github.com/tnahs/readstor"
repository = "https://github.com/tnahs/readstor"
keywords = ["apple", "books", "ibooks", "highlights", "macos"]
categories = ["command-line-utilities"]
edition = "2021"
include = [
  "src/**/*.rs",
  "templates/flat/template.jinja2", # Default template
  "README.md",
  "extra/logo/logo-256.png",
  "LICENSE-APACHE",
  "LICENSE-MIT",
]

[dependencies]
color-eyre = "0.6.1"
deunicode = "1.3.1"
env_logger = "0.9.0"
glob = "0.3.0"
home = "0.5.3"
log = "0.4.14"
once_cell = "1.9.0"
pathdiff = "0.2.1"
plist = "1.3.1"
regex = "1.5.4"
rusqlite = "0.27.0"
serde_json = "1.0.79"
serde_yaml = "0.9.10"
sysinfo = "0.23.4"
tera = "1.15.0"
thiserror = "1.0.30"
walkdir = "2.3.2"

[dependencies.chrono]
version = "0.4.19"
features = ["serde"]

[dependencies.clap]
version = "4.0"
features = ["derive"]

[dependencies.serde]
version = "1.0.136"
features = ["derive"]

[dev-dependencies]
assert_cmd = "2.0.4"
