[package]
name = "readstor"
version = "0.1.0"
description = "A CLI for Apple Books annotations"
readme = "README.md"
license-file = "LICENSE.txt"
homepage = "https://github.com/tnahs/readstor_rs"
repository = "https://github.com/tnahs/readstor_rs"
keywords = ["apple", "macos", "books", "ibooks", "highlights"]
categories = ["command-line-utilities"]
edition = "2021"
exclude = ["scripts/*", ".vscode/*"]

[dependencies]
anyhow = "1.0"
glob = "0.3"
home = "0.5"
log = "0.4"
loggerv = "0.7"
once_cell = "1.8"
plist = "1.0"
regex = "1.5"
rusqlite = "0.26"
serde_json = "1.0"
sysinfo = "0.20"
tera = "1"
thiserror = "1.0"

[dependencies.chrono]
version = "0.4"
features = ["serde"]

[dependencies.serde]
version = "1.0"
features = ["derive"]

[dependencies.structopt]
version = "0.3"
default-features = false

[dev-dependencies]
assert_cmd = "2.0"
