[package]
name = "readstor"
version = "0.3.0"
description = "A CLI for Apple Books annotations"
readme = "README.md"
license = "MIT OR Apache-2.0"
homepage = "https://github.com/tnahs/readstor"
repository = "https://github.com/tnahs/readstor"
keywords = ["apple", "macos", "books", "ibooks", "highlights"]
categories = ["command-line-utilities"]
edition = "2021"
exclude = ["scripts/*", ".vscode/*", "docs/*", "TODO.md"]

[dependencies]
color-eyre = "0.6.0"
env_logger = "0.9.0"
glob = "0.3.0"
home = "0.5.3"
log = "0.4.14"
once_cell = "1.9.0"
plist = "1.3.1"
regex = "1.5.4"
rusqlite = "0.26.3"
serde_json = "1.0.79"
sysinfo = "0.23.2"
tera = "1.15.0"
thiserror = "1.0.30"
walkdir = "2.3.2"

[dependencies.chrono]
version = "0.4.19"
features = ["serde"]

[dependencies.clap]
version = "3.0.14"
features = ["derive"]

[dependencies.serde]
version = "1.0.136"
features = ["derive"]

[dev-dependencies]
assert_cmd = "2.0.4"
