[[language]]
name = "rust"
auto-format = true
text-width = 100

[language-server.rust-analyzer.config]
checkOnSave.command = "clippy"

[[language]]
name = "markdown"
auto-format = true
text-width = 100
