[env]
READSTOR_DEV = "1"
READSTOR_LOG = "debug"

[registries]
staging = { index = "https://github.com/rust-lang/staging.crates.io-index" }

[alias]
lint = """\
    clippy \
        --all-targets \
        --all-features \
        -- \
        --warn clippy::pedantic \
        --warn clippy::cargo \
    """
docs = "doc --no-deps --open"
