name: build

on:
  workflow_dispatch:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+

jobs:
  ci:
    uses: ./.github/workflows/ci.yml

  build:
    name: Build for ${{ matrix.name }}
    needs: ci
    runs-on: macos-latest
    strategy:
      matrix:
        include:
          - name: Apple Silicon
            arch: arm64
            target: aarch64-apple-darwin
          - name: Intel
            arch: amd64
            target: x86_64-apple-darwin
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Rust
        run: |
          rustup update stable
          rustup default stable
          rustup target add ${{ matrix.target }}

      - name: Build binary
        run: cargo build --release --target ${{ matrix.target }}

      - name: Build names
        run: |
          binary="$(cargo read-manifest | jq -r '.name')"
          version="${{ github.ref_name }}"
          arch="${{ matrix.arch }}"

          # [BINARY]-[VERSION]-darwin-[ARCH].tar.gz
          archive="${binary}-${version#v}-darwin-${arch}.tar.gz"

          echo "BINARY="${binary}"" >> $GITHUB_ENV
          echo "ARCHIVE="${archive}"" >> $GITHUB_ENV

      - name: Create archive
        run: >
          tar
          --create
          --gzip
          --file="${{ env.ARCHIVE }}"
          --directory="./target/${{ matrix.target }}/release/"
          "${{ env.BINARY }}"

      - name: Create draft release
        uses: softprops/action-gh-release@v2
        with:
          files: "${{ env.ARCHIVE }}"
          draft: true
