name: ci

on:
  workflow_call:
  pull_request:
  push:

jobs:
  rust-checks:
    name: Run cargo ${{ matrix.task.name }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        task:
          - name: check
            command: cargo check
          - name: rustfmt
            command: cargo fmt --all -- --check
          - name: clippy
            command: cargo clippy --all-targets --all-features -- -D warnings
          - name: test
            command: cargo test
          - name: publish (dry-run)
            command: cargo publish --dry-run
          - name: package
            command: cargo package --list
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Rust
        run: |
          rustup update stable
          rustup default stable
          rustup component add clippy
          rustup component add rustfmt

      - name: Run ${{ matrix.task.name }}
        run: ${{ matrix.task.command }}
