name: docs

on:
  workflow_dispatch:
  push:
    branches:
      - main
    tags:
      - v[0-9]+.[0-9]+.[0-9]+

jobs:
  book:
    name: Build & Deploy Book
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install mdBook
        uses: peaceiris/actions-mdbook@v2
        with:
          mdbook-version: "latest"

      - name: Build
        run: mdbook build ./book

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./book/build
          # Tagged commits go to '/latest' and un-tagged commits go to '/dev'.
          destination_dir: ${{ startsWith(github.ref, 'refs/tags/v') && 'latest' || 'dev' }}
