name: docs

on:
  workflow_dispatch:
  push:
    branches:
      - main
    tags:
      - v[0-9]+.[0-9]+.[0-9]+

jobs:
  book:
    name: Build & Deploy Book
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Install mdBook
        uses: peaceiris/actions-mdbook@v1
        with:
          mdbook-version: "latest"
      - name: Build book
        run: mdbook build ./book
      - name: Deploy to latest
        if: ${{ startsWith(github.ref, 'refs/tags/v') }}
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./book/build
          destination_dir: latest
      - name: Deploy to dev
        if: ${{ !startsWith(github.ref, 'refs/tags/v') }}
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./book/build
          destination_dir: dev
