name: publish-crates-io

on:
  workflow_dispatch:

jobs:
  ci:
    uses: ./.github/workflows/ci.yml

  publish:
    name: Publish to 'crates.io'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Rust
        run: |
          rustup update stable
          rustup default stable

      - name: Publish
        run: cargo publish
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
