name: release

on:
  workflow_dispatch:
  push:
    tags:
      - "*"

jobs:
  ci:
    uses: ./.github/workflows/ci.yml

  release:
    name: Build/Release to ${{ matrix.arch }}
    needs: ci
    runs-on: macos-latest
    strategy:
      matrix:
        include:
          - arch: Apple Silicon
            target: aarch64-apple-darwin
            artifact: ${{ github.event.repository.name }}
            archive: ${{ github.event.repository.name }}-${{ github.ref_name }}-darwin-arm64.tar.gz
          - arch: Intel
            target: x86_64-apple-darwin
            artifact: ${{ github.event.repository.name }}
            archive: ${{ github.event.repository.name }}-${{ github.ref_name }}-darwin-amd64.tar.gz
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.target }}
          override: true
      - name: Build release
        run: cargo build --release --target ${{ matrix.target }}
      - name: Compress release
        run: >
          tar
          --create
          --gzip
          --file=${{ matrix.archive }}
          --directory=./target/${{ matrix.target }}/release/
          ${{ matrix.artifact }}
      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ matrix.archive }}

  homebrew:
    name: Release to `homebrew-formulas`
    needs: release
    runs-on: ubuntu-latest
    steps:
      - uses: Justintime50/homebrew-releaser@v1
        with:
          homebrew_owner: tnahs
          homebrew_tap: homebrew-formulas
          github_token: ${{ secrets.HOMEBREW_GITHUB_TOKEN }}
          target_darwin_amd64: true
          target_darwin_arm64: true
          install: 'bin.install "readstor"'
